# Usa o servidor web Nginx (super leve e rápido)
FROM nginx:alpine

# Copia todos os seus arquivos (html, css, js, imagens) para a pasta pública do Nginx
COPY . /usr/share/nginx/html

# O Nginx expõe a porta 80 por padrão